<?php
$this->headTitle('Ajouter une société')
?>
<?php $this->headStyle()->captureStart() ?>
/*
label, input {
    display: block;
}
*/
<?php $this->headStyle()->captureEnd() ?>
<h2><?php echo $this->translate('Ajouter un contact'); ?></h2>
<?=$this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate'))?>
<div class="form-group <?php if($form->get('nom')->getMessages()) echo "has-error"; ?>">
    <?=$this->formLabel($form->get('nom')->setLabelAttributes(array('class' => 'col-sm-2 control-label')))?>
    <div class="col-sm-10">
        <?=$this->formElement($form->get('nom')->setAttribute('class', 'form-control'))?>
    </div>
    <span class="help-block">
        <?=$this->formElementErrors($form->get('nom'))?>
    </span>
</div>
<div class="form-group <?php if($form->get('siteWeb')->getMessages()) echo "has-error"; ?>">
    <?=$this->formLabel($form->get('siteWeb')->setLabelAttributes(array('class' => 'col-sm-2 control-label')))?>
    <div class="col-sm-10">
        <?=$this->formElement($form->get('siteWeb')->setAttribute('class', 'form-control'))?>
    </div>
    <span class="help-block">
        <?=$this->formElementErrors($form->get('siteWeb'))?>
    </span>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Ajouter</button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>