<?php
$title = 'Supprimer une société';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Êtes-vous sur de supprimer la société
    '<?php echo $this->escapeHtml($societe->getNom()); ?>'?
</p>
<?php
$url = $this->url('societe/delete', array(
    'id' => $this->id,
    ));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $societe->getId(); ?>" />
        <input class="btn btn-primary" type="submit" name="del" value="Oui" />
        <input class="btn btn-primary" type="submit" name="del" value="Non" />
    </div>
</form>