<?php
$this->headTitle('Liste des sociétés');
?>
<?php $this->headStyle()->captureStart() ?>
h1 {
    text-decoration: underline;
}
<?php $this->headStyle()->captureEnd() ?>
<?php $this->inlineScript()->captureStart() ?>
//alert('Coucou');
<?php $this->inlineScript()->captureEnd() ?>
<?php foreach($this->flashMessenger()->getSuccessMessages() as $m): ?>
<?=$this->bootstrapAlert($m)?>
<?php endforeach; ?>
<?php //echo $this->bootstrapAlert('Coucou'); ?>
<h1>Liste des sociétés</h1>
<table class="table table-striped">
    <?php foreach ($societes as $societe): ?>
    <tr>
        <td>
            <?=$this->escapeHtml($societe->getNom())?> <?=$this->escapeHtml($societe->getNom())?>
        </td>
        <td>
            <a href="<?=$this->url('societe/show', array('id' => $this->escapeUrl($societe->getId())))?>" class="btn btn-primary btn-xs">Détails</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>